config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  
  root 'page#index'
  get 'page/vote' => 'page#vote'
  get 'page/test' => 'page#test'
  resources :votes
  resources :questions

end

app/models/answer.rb
class Answer
	include Mongoid::Document
	
	field :created_at,      type: DateTime
  field :updated_at,      type: DateTime
  field :answer,					type: String
  field :question_id, 		type: Integer

  belongs_to :question
  has_many :votes, dependent: :destroy
  validates :answer, presence: true, length: { minimum: 3 }
end

app/models/question.rb
class Question
	include Mongoid::Document

	field :created_at,      type: DateTime
  field :updated_at,      type: DateTime
  field :question,				type: String
  field :result_type,			type: String
  field :user_id,         type: Integer
	
  belongs_to :user
  validates :question, presence: true, length: { minimum: 3 }
  has_many :answers, dependent: :destroy


end

app/models/user.rb
class User
	include Mongoid::Document
	include Mongoid::Search

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]["$oid"])
      record if record && record.authenticatable_salt == salt
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :email,              						type: String,  default: ""
  field :encrypted_password, 						type: String,  default: ""
  field :reset_password_token, 					type: String
  field :reset_password_sent_at, 				type: DateTime
  field :remember_created_at, 					type: DateTime
  field :sign_in_count, 								type: Integer, default: 0
  field :current_sign_in_at, 						type: DateTime
  field :last_sign_in_at, 							type: DateTime
  field :current_sign_in_ip, 						type: String
  field :last_sign_in_ip, 							type: String
  field :created_at, 										type: DateTime
  field :updated_at, 										type: DateTime
  field :username,                      type: String
  field :firstname,                     type: String
  field :lastname,                      type: String
  field :town,                          type: String
  field :country,                          type: String
  field :sex,                           type: String
  field :birthday,                      type: DateTime
  
  acts_as_token_authenticatable
  field :authentication_token

  has_many :questions, dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote
	include Mongoid::Document

  field :answer_id,       type: Integer
  field :user_id,         type: Integer
  field :created_at,      type: DateTime
  field :updated_at,      type: DateTime
  field :answer_id,       type: String

    
  belongs_to :answer
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def test
  	if params[:token].nil?
  		@user = nil
  	else
  		@user = User.where(authentication_token: params[:token]).first
  		render json: @user
  	end
  end

  def vote

  	@question = Question.all
  	if user_signed_in?
  		raise current_user.inspect
  		@votes = Vote.where(user_id: current_user.id)
  	end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def get_full_error_msg obj
		if obj.errors.any?
  			full_msg = ""
  			if obj.errors.count == 1
  				full_msg += "1 error: " 
   			else
  				full_msg += obj.errors.count.to_s + " errors: "
	   		end
    		obj.errors.full_messages.each do |msg|
      			full_msg += msg + ". " 
    		end
    		return full_msg
    	end
	end

	def create
		question = Question.new question_params
		question.user_id = current_user.id
		if question.save
			params[:question].each do |key, value|
				save = false
				if key.to_s == "answer"
					answer = Answer.new answer_params
					answer.question_id = question.id
					save = true
				elsif key.to_s != "question" && key.to_s != "result_type" 
					answer = Answer.new({:answer => value})
					answer.question_id = question.id
					save = true
				end
				if save && !answer.save
					full_msg = get_full_error_msg answer
    				redirect_to root_path, alert: full_msg
    				return
   				end
   			end
   			redirect_to root_path, notice: "Your question has been added"
		else
			full_msg = get_full_error_msg question
			redirect_to root_path, alert: full_msg
		end
	end

	def destroy
		q = Question.find(params[:id])
		if q.destroy
			redirect_to root_path, notice: "Your question has been deleted"
		else
			redirect_to root_path, alert: "Delete question failed"
		end
	end

	def update
		@question = Question.find(params[:id])
		if @question.update(question_params)
			redirect_to root_path, notice: "Your question has been updated"
		else
			full_msg = get_full_error_msg @question 
			redirect_to root_path, alert: full_msg
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def show
		@question = Question.find(params[:id])
		@reponses = Answer.where(question_id: params[:id])
	end

	private

	def question_params
		params.require(:question).permit(:question, :result_type)
	end

	def answer_params
		params.require(:question).permit(:answer)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		a = Answer.find(params[:answer_id])
		vote = Vote.new
		vote.answer_id = params[:answer_id]
		vote.user_id = current_user.id
		vote.save
		redirect_to page_vote_path, notice: "You have voted"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>21Questions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
  <%= link_to "Index", root_path, :class => 'navbar-link'  %> |
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Vote", page_vote_path %> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1>index</h1>
<% if user_signed_in? %>
	<table>
		<tr>
			<th>Your questions</th><br><br>
		</tr>
		<% for e in current_user.questions %>
			<tr>
				<td>
					Q: <%= e.question %>
					<%= link_to "Edit", edit_question_path(e) %>
					<%= link_to "Delete", e, method: :delete %>
					<br>Type: <%= e.result_type %> 
					<% for a in e.answers %>
						<br>R: <%= a.answer %>
					<% end %><br><br>
				</td>
			</tr>
		<% end %>
	</table>
	<br>
	<%= render 'questions/form' %>
<% else %>
<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
<% end %>

app/views/page/test.html.erb
<% if @user.nil? %>
	<h1>Give token please</h1>
<% else %>
 	<h1><%= @user.email %></h1>
<% end %>

app/views/page/vote.html.erb
<table>
		<h1>Votez !</h1>
		<% for a in @question %>
			<div><%= a.question %> <%= link_to "Votez", question_path(a) %></div>
		<% end %>
</table>
<h1>Vos votes</h1>
<% for v in @votes %>
	<% vote = Answer.find(v.answer_id) %>
	<p><%= vote.answer %></p>
<% end %>

app/views/questions/_form.html.erb
<script type="text/javascript">
    $(document).ready(function()
    {
        $('#add_input').click(function()
        {
        	var c = $("#to_change input:last").clone();
            var value = "question[answer" + $("#to_change input").length + "]";
            c.attr("name", value)
            $("#to_change").append('<br>');
            $("#to_change").append(c);
        });
        $('#remove_input').click(function()
        {
        	if ($("#to_change input").length > 1) {
        		$("#to_change input:last").remove();
        		$("#to_change br:last").remove();
        	}
        });
    });
</script> 
<%= form_for :question, url: questions_path do |f| %>
	<div style="width: 25%;">
	<p>
		<%= f.label :question %><br>
		<%= f.text_field :question, class: "form-control" %>
	</p>
	<p>
		<%= f.label :result_type %><br>
		<%= f.select :result_type, ["binaire", "QCM", "QCU"], {}, class: "form-control" %>
	</p>
	<p id="to_change">
		<%= f.label :answer %><br>
		<%= f.text_field :answer, class: "form-control" %>
	</p>
		
	<p>
		<%= f.submit class: "btn btn-large btn-primary" %>
		<button id="add_input" type="button" class="btn btn-default btn-lg">
			<span class="glyphicon glyphicon-plus-sign" ></span>
		</button>
		<button id="remove_input" type="button" class="btn btn-default btn-lg" >
			<span class="glyphicon glyphicon-minus-sign" ></span>
		</button>
	</p>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>
<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <p>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </p>
   <p>
	    <%= f.label :result_type %><br>
		<%= f.select :result_type, ["binaire", "QCM", "QCU"] %>
	</p>
  <p>
    <%= f.submit class: "btn btn-large btn-primary"%>
  </p>
<% end %>

app/views/questions/show.html.erb
<h1>Questions: <%= @question.question %></h1>
<%= form_for Vote.new do |f| %>
	<% for a in @reponses %>
		<p><%= a.answer%> <br>
       	<%= check_box_tag 'answer_id', a.id %><br>
	<% end %>
	<%= f.submit class: "btn btn-large btn-primary" %>
<% end %>